name: Metrics

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node_modules-
      - name: Install dependencies
        run: yarn

      - name: Run test coverage
        run: yarn coverage

      - name: Generate Code Coverage report
        id: code_coverage
        uses: barecheck/code-coverage-action@v0.1-beta.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: './coverage/lcov.info'

      - name: Send Code Coverage metrics
        id: send-metrics
        uses: barecheck/newrelic-metric-action@v0.2-beta.1
        with:
          insertApiKey: ${{ secrets.NEW_RELIC_METRICS_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          region: EU
          application: codeCoverageAction
          metricName: codeCoverage
          metricValue: ${{ steps.code_coverage.outputs.percentage }}
